local AL = AtlasLoot.L
local GREY = "|cff999999"
local RED = "|cffff0000"
local WHITE = "|cffFFFFFF"
local GREEN = "|cff1eff00"
local PURPLE = "|cff9F3FFF"
local BLUE = "|cff0070dd"
local ORANGE = "|cffFF8400"
local DEFAULT = "|cffFFd200"

AtlasLoot_Data.MENUS = {
    -- Sets
    SETMENU = {
        { 1, "PRE60SET", "INV_Sword_43", AL["Sets"] },
        { 2, "ZGSET", "INV_Sword_55", AL["Zul'Gurub Sets"] },
        { 3, "AQ20SET", "INV_Axe_15", AL["Ruins of Ahn'Qiraj Sets"] },
        { 4, "AQ40SET", "INV_Shoulder_35", AL["Temple of Ahn'Qiraj Sets"] },
        { 5, "KARASET", "INV_Staff_Medivh", AL["Karazhan"].." "..AL["Sets"] },
        { 6, "TMHSET", "INV_Misc_Horn_01", AL["Timbermaw Hold"].." "..AL["Sets"] },
        { 8, "Legendaries", "INV_Hammer_Unique_Sulfuras", AL["Legendary Items"] },
        { 9, "RarePets1", "Ability_Seal", AL["Rare Pets"] },
        { 10, "RareMounts", "INV_Misc_QirajiCrystal_05", AL["Rare Mounts"] },
        { 11, "WorldEpics1", "INV_Gauntlets_30", AL["World Epics"] },
        { 12, "Tabards", "INV_Shirt_GuildTabard_01", AL["Tabards"] },
        { 16, "T0SET", "INV_Helmet_24", AL["Dungeon Sets"] },
        { 17, "T1SET", "INV_Helmet_09", AL["Tier 1 Sets"] },
        { 18, "T2SET", "INV_Helmet_74", AL["Tier 2 Sets"] },
        { 19, "T3SET", "INV_Helmet_58", AL["Tier 3 Sets"] },
    },
    PRE60SET = {
        { 1, nil, "INV_Pants_12", AL["Defias Leather"], ORANGE..AL["The Deadmines"], AtlasLoot_Data.AtlasLootSetItems.DeadminesC },
        { 2, nil, "INV_Shirt_16", AL["Embrace of the Viper"], ORANGE..AL["Wailing Caverns"], AtlasLoot_Data.AtlasLootSetItems.WailingC },
        { 3, nil, "INV_Gauntlets_19", AL["Chain of the Scarlet Crusade"], ORANGE..AL["Scarlet Monastery"], AtlasLoot_Data.AtlasLootSetItems.ScarletC },
        { 4, nil, "INV_Helmet_01", AL["The Gladiator"], ORANGE..AL["Blackrock Depths"], AtlasLoot_Data.AtlasLootSetItems.BlackrockdC },
        { 5, nil, "INV_Boots_Cloth_05", AL["Ironweave Battlesuit"], ORANGE..AL["Various Locations"], AtlasLoot_Data.AtlasLootSetItems.IronweaveC },
        { 6, nil, "INV_Boots_02", AL["The Postmaster"], ORANGE..AL["Stratholme"], AtlasLoot_Data.AtlasLootSetItems.StratC },
        { 7, nil, "INV_Shoulder_02", AL["Necropile Raiment"], ORANGE..AL["Scholomance"], AtlasLoot_Data.AtlasLootSetItems.ScholoClothC },
        { 8, nil, "INV_Belt_16", AL["Cadaverous Garb"], ORANGE..AL["Scholomance"], AtlasLoot_Data.AtlasLootSetItems.ScholoLeatherC },
        { 9, nil, "INV_Gauntlets_26", AL["Bloodmail Regalia"], ORANGE..AL["Scholomance"], AtlasLoot_Data.AtlasLootSetItems.ScholoMailC },
        { 10, nil, "INV_Belt_12", AL["Deathbone Guardian"], ORANGE..AL["Scholomance"], AtlasLoot_Data.AtlasLootSetItems.ScholoPlateC },
        { 11, nil, "INV_Jewelry_Talisman_13", AL["Scourge Invasion"], ORANGE..AL["Various Locations"], AtlasLoot_Data.AtlasLootSetItems.ScourgeInvasionC },
        { 12, nil, "INV_Weapon_ShortBlade_16", AL["Spider's Kiss"], ORANGE..AL["Lower Blackrock Spire"], AtlasLoot_Data.AtlasLootSetItems.SpiderKissC },
        { 13, nil, "INV_Sword_43", AL["Dal'Rend's Arms"], ORANGE..AL["Upper Blackrock Spire"], AtlasLoot_Data.AtlasLootSetItems.DalRendC },
        { 14, nil, "INV_Misc_MonsterScales_15", AL["Shard of the Gods"], ORANGE..AL["Various Locations"], AtlasLoot_Data.AtlasLootSetItems.ShardOfGodsC },
        { 15, nil, "INV_Misc_MonsterClaw_04", AL["Spirit of Eskhandar"], ORANGE..AL["Various Locations"], AtlasLoot_Data.AtlasLootSetItems.SpiritofEskhandarC },
    },
    ZGSET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootSetItems.ZGPriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootSetItems.ZGMageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootSetItems.ZGWarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootSetItems.ZGRogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootSetItems.ZGDruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootSetItems.ZGHunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootSetItems.ZGShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootSetItems.ZGPaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootSetItems.ZGWarriorC },
        { 16, nil, "INV_Jewelry_Ring_46", AL["Zul'Gurub Rings"], "", AtlasLoot_Data.AtlasLootSetItems.ZGRingsC },
        { 17, nil, "INV_Weapon_Hand_01", AL["Primal Blessing"], "", AtlasLoot_Data.AtlasLootSetItems.PrimalBlessingC },
        { 18, nil, "INV_Sword_55", AL["The Twin Blades of Hakkari"], "", AtlasLoot_Data.AtlasLootSetItems.HakkariBladesC },
    },
    AQ20SET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20PriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20MageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20WarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20RogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20DruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20HunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20ShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20PaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootSetItems.AQ20WarriorC },
    },
    AQ40SET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40PriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40MageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40WarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40RogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40DruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40HunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40ShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40PaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootSetItems.AQ40WarriorC },
    },
    T0SET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootSetItems.T0PriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootSetItems.T0MageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootSetItems.T0WarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootSetItems.T0RogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootSetItems.T0DruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootSetItems.T0HunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootSetItems.T0ShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootSetItems.T0PaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootSetItems.T0WarriorC },
    },
    T1SET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootSetItems.T1PriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootSetItems.T1MageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootSetItems.T1WarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootSetItems.T1RogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootSetItems.T1DruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootSetItems.T1HunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootSetItems.T1ShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootSetItems.T1PaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootSetItems.T1WarriorC },
    },
    T2SET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootSetItems.T2PriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootSetItems.T2MageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootSetItems.T2WarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootSetItems.T2RogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootSetItems.T2DruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootSetItems.T2HunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootSetItems.T2ShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootSetItems.T2PaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootSetItems.T2WarriorC },
    },
    T3SET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootSetItems.T3PriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootSetItems.T3MageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootSetItems.T3WarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootSetItems.T3RogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootSetItems.T3DruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootSetItems.T3HunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootSetItems.T3ShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootSetItems.T3PaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootSetItems.T3WarriorC },
    },
    KARASET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootSetItems.T35PriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootSetItems.T35MageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootSetItems.T35WarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootSetItems.T35RogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootSetItems.T35DruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootSetItems.T35HunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootSetItems.T35ShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootSetItems.T35PaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootSetItems.T35WarriorC },
    },
    TMHSET = {
        { 1, nil, "INV_Chest_Cloth_43", AL["Majesty of the Stag"], ORANGE..AL["Cloth"], AtlasLoot_Data.AtlasLootSetItems.TMHClothHealer },
        { 2, nil, "INV_Chest_Cloth_43", AL["Wisdom of the Deer"], ORANGE..AL["Cloth"], AtlasLoot_Data.AtlasLootSetItems.TMHClothDps },
        { 3, nil, "INV_Chest_Chain_15", AL["Rage of the Ursa"], ORANGE..AL["Leather"], AtlasLoot_Data.AtlasLootSetItems.TMHLeather },
        { 4, nil, "INV_Chest_Chain_15", AL["Might of the Hyppogryph"], ORANGE..AL["Mail"], AtlasLoot_Data.AtlasLootSetItems.TMHMail },
        { 5, nil, "INV_Chest_Plate02", AL["Pride of the Moose"], ORANGE..AL["Plate"], AtlasLoot_Data.AtlasLootSetItems.TMHPlate },
    },

    -- PVP
    PVPMENU = {
        { 1, "AVRepMenu", "INV_Jewelry_Necklace_21", AL["Alterac Valley"] },
        { 2, "ABRepMenu", "INV_Jewelry_Amulet_07", AL["Arathi Basin"] },
        { 3, "WSGRepMenu", "INV_Misc_Rune_07", AL["Warsong Gulch"] },
        { 4, "BRRepMenu", "inv_jewelry_ring_04", AL["Blood Ring"] },
        { 16, "PvP60Accessories1", "INV_Jewelry_Talisman_09", AL["PvP Accessories"], ORANGE..AL["Rank 2-9"] },
        { 17, "PVPSET", "INV_Helmet_05", AL["PvP Armor Sets"], ORANGE..AL["Rank 7-13"] },
        { 18, "PVPWeapons1", "INV_Sword_11", AL["PvP Weapons"], ORANGE..AL["Rank 14"] },
        { 19, "PvPMountsPvP", "Ability_Mount_RidingHorse", AL["PvP Mounts"], ORANGE..AL["Rank 11"] },
    },
    BRRepMenu = {
        { 1, "BRRepFriendly", "inv_jewelry_ring_04", AL["Friendly"] },
        { 2, "BRRepHonored", "inv_jewelry_ring_04", AL["Honored"] },
        { 3, "BRRepRevered", "inv_jewelry_ring_04", AL["Revered"] },
        { 4, "BRRepExalted", "inv_jewelry_ring_04", AL["Exalted"] },
        { 5, "BRRepTokens", "inv_jewelry_ring_04", AL["Token of Blood Rewards"] },
    },
    WSGRepMenu = {
        { 1, nil, "INV_Misc_Rune_07", RED..AL["Friendly"] },
        { 2, "WSGRepFriendly", "INV_Misc_Rune_07", "10-60" },
        { 4, nil, "INV_Misc_Rune_07", RED..AL["Honored"] },
        { 5, "WSGRepHonored1019", "INV_Misc_Rune_07", "10-19" },
        { 6, "WSGRepHonored2029", "INV_Misc_Rune_07", "20-29" },
        { 7, "WSGRepHonored3039", "INV_Misc_Rune_07", "30-39" },
        { 8, "WSGRepHonored4049", "INV_Misc_Rune_07", "40-49" },
        { 9, "WSGRepHonored5059", "INV_Misc_Rune_07", "50-59" },
        { 16, nil, "INV_Misc_Rune_07", RED..AL["Revered"] },
        { 17, "WSGRepRevered1019", "INV_Misc_Rune_07", "10-19" },
        { 18, "WSGRepRevered2029", "INV_Misc_Rune_07", "20-29" },
        { 19, "WSGRepRevered3039", "INV_Misc_Rune_07", "30-39" },
        { 20, "WSGRepRevered4049", "INV_Misc_Rune_07", "40-49" },
        { 21, "WSGRepRevered5059", "INV_Misc_Rune_07", "50-59" },
        { 23, nil, "INV_Misc_Rune_07", RED..AL["Exalted"] },
        { 24, "WSGRepExalted4049", "INV_Misc_Rune_07", "40-49" },
        { 25, "WSGRepExalted5059", "INV_Misc_Rune_07", "50-59" },
        { 26, "WSGRepExalted60", "INV_Misc_Rune_07", "60" },
    },
    ABRepMenu = {
        { 1, nil, "INV_Jewelry_Amulet_07", RED..AL["Friendly"] },
        { 2, "ABRepFriendly", "INV_Jewelry_Amulet_07", "10-60" },
        { 4, nil, "INV_Jewelry_Amulet_07", RED..AL["Honored"] },
        { 5, "ABRepHonored2029", "INV_Jewelry_Amulet_07", "20-29" },
        { 6, "ABRepHonored3039", "INV_Jewelry_Amulet_07", "30-39" },
        { 7, "ABRepHonored4049", "INV_Jewelry_Amulet_07", "40-49" },
        { 8, "ABRepHonored5059", "INV_Jewelry_Amulet_07", "50-59" },
        { 16, nil, "INV_Jewelry_Amulet_07", RED..AL["Revered"] },
        { 17, "WSGRepRevered2029", "INV_Jewelry_Amulet_07", "20-29" },
        { 18, "WSGRepRevered3039", "INV_Jewelry_Amulet_07", "30-39" },
        { 19, "WSGRepRevered4049", "INV_Jewelry_Amulet_07", "40-49" },
        { 20, "WSGRepRevered5059", "INV_Jewelry_Amulet_07", "50-59" },
        { 22, nil, "INV_Jewelry_Amulet_07", RED..AL["Exalted"] },
        { 23, "WSGRepExalted60", "INV_Jewelry_Amulet_07", "60" },
    },
    AVRepMenu = {
        { 1, "AVRepFriendly", "INV_Jewelry_Necklace_21", AL["Friendly Reputation Rewards"] },
        { 2, "AVRepHonored", "INV_Jewelry_Necklace_21", AL["Honored Reputation Rewards"] },
        { 3, "AVRepRevered", "INV_Jewelry_Necklace_21", AL["Revered Reputation Rewards"] },
        { 4, "AVRepExalted", "INV_Jewelry_Necklace_21", AL["Exalted Reputation Rewards"] },
        { 5, "AVKorrak", "INV_Jewelry_Necklace_21", AL["Korrak the Bloodrager"] },
        { 6, "AVLokholarIvus", "INV_Jewelry_Necklace_21", AL["Ivus & Lokholar"] },
    },
    PVPSET = {
        { 1, nil, "CLASSpriest", "|cffffffff"..AL["Priest"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPPriestC },
        { 2, nil, "CLASSmage", "|cff68ccef"..AL["Mage"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPMageC },
        { 3, nil, "CLASSwarlock", "|cff9382c9"..AL["Warlock"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPWarlockC },
        { 4, nil, "CLASSrogue", "|cfffff468"..AL["Rogue"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPRogueC },
        { 5, nil, "CLASSdruid", "|cffff7c0a"..AL["Druid"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPDruidC },
        { 6, nil, "CLASShunter", "|cffaad372"..AL["Hunter"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPHunterC },
        { 7, nil, "CLASSshaman", "|cff2773ff"..AL["Shaman"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPShamanC },
        { 8, nil, "CLASSpaladin", "|cfff48cba"..AL["Paladin"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPPaladinC },
        { 9, nil, "CLASSwarrior", "|cffc69b6d"..AL["Warrior"], "", AtlasLoot_Data.AtlasLootGeneralPvPItems.PVPWarriorC },
    },

    -- Reputation
    REPMENU = {
        { 1, "Argent1", "INV_Jewelry_Talisman_08", AL["Argent Dawn"] },
        { 2, "AQBroodRings", "INV_Jewelry_Ring_40", AL["Brood of Nozdormu"] },
        { 3, "Darkmoon", "INV_Misc_Ticket_Tarot_Maelstrom_01", AL["Darkmoon Faire"] },
        { 4, "WaterLords1", "Spell_Frost_SummonWaterElemental_2", AL["Hydraxian Waterlords"] },
        { 5, "Thorium1", "INV_Ingot_Mithril", AL["Thorium Brotherhood"] },
        { 6, "Cenarion1", "Spell_Nature_HealingTouch", AL["Cenarion Circle"] },
        { 7, "Shendralar", "INV_Misc_Book_04", AL["Shen'dralar"] },
        { 8, "Stormwind", "race_human", AL["Stormwind"], BLUE..AL["Alliance"] },
        { 9, "Ironforge", "race_dwarf", AL["Ironforge"], BLUE..AL["Alliance"] },
        { 10, "GnomereganExiles", "race_gnome", AL["Gnomeregan Exiles"], BLUE..AL["Alliance"] },
        { 11, "Darnassus", "race_night_elf", AL["Darnassus"], BLUE..AL["Alliance"] },
        { 12, "Helf", "race_high_elf", AL["Silvermoon Remnant"], BLUE..AL["Alliance"] },
        { 13, "Dalaran", "Spell_Holy_MagicalSentry", AL["Dalaran"], BLUE..AL["Alliance"] },
        { 14, "Wintersaber1", "Ability_Mount_PinkTiger", AL["Wintersaber Trainers"], BLUE..AL["Alliance"] },
        { 15, "Wildhammer", "Ability_Hunter_EagleEye", AL["Wildhammer Clan"], BLUE..AL["Alliance"] },
        { 16, "DraeneiExiles", "INV_Enchant_ShardGlowingLarge", AL["Draenei Exiles"] },
        { 17, "Bloodsail1", "INV_Helmet_66", AL["Bloodsail Buccaneers"] },
        { 18, "Zandalar1", "INV_Misc_Coin_08", AL["Zandalar Tribe"] },
        { 19, "Timbermaw", "INV_Misc_Horn_01", AL["Timbermaw Hold"] },
        { 20, "Wardens1", "INV_Misc_Head_Dragon_Bronze", AL["Wardens of Time"] },
        { 21, "GelkisClan1", "INV_Misc_Head_Centaur_01", AL["Gelkis Clan Centaur"] },
        { 22, "MagramClan1", "INV_Misc_Head_Centaur_01", AL["Magram Clan Centaur"] },
        { 23, "Orgrimmar", "race_orc", AL["Orgrimmar"], RED..AL["Horde"] },
        { 24, "DarkspearTrolls", "race_troll", AL["Darkspear Trolls"], RED..AL["Horde"] },
        { 25, "ThunderBluff", "race_tauren", AL["Thunder Bluff"], RED..AL["Horde"] },
        { 26, "Undercity", "race_forsaken", AL["Undercity"], RED..AL["Horde"] },
        { 27, "DurotarLaborUnion", "race_goblin", AL["Durotar Labor Union"], RED..AL["Horde"] },
        { 28, "Revantusk", "INV_Misc_Head_Troll_01", AL["Revantusk Trolls"], RED..AL["Horde"] },
        { 29, "EarthenRing", "Spell_Nature_EarthShock", AL["Earthen Ring"], RED..AL["Horde"] },
    },

    -- Crafting
    CRAFTINGMENU = {
		{ 1, "ALCHEMYMENU", "Trade_Alchemy", AL["Alchemy"] },
		{ 2, "ENCHANTINGMENU", "Trade_Engraving", AL["Enchanting"] },
		{ 3, "ENGINEERINGMENU", "Trade_Engineering", AL["Engineering"] },
		{ 4, "LEATHERWORKINGMENU", "INV_Misc_ArmorKit_17", AL["Leatherworking"] },
		{ 5, "SMITHINGMENU", "Trade_BlackSmithing", AL["Blacksmithing"] },
		{ 6, "TAILORINGMENU", "Trade_Tailoring", AL["Tailoring"] },
		{ 7, "JEWELCRAFTMENU", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"] },
		{ 9, "Herbalism1", "Trade_Herbalism", AL["Herbalism"] },
		{ 10, "Mining1", "Trade_Mining", AL["Mining"] },
		{ 11, "CookingApprentice1", "INV_Misc_Food_15", AL["Cooking"] },
		{ 12, "FirstAid1", "Spell_Holy_SealOfSacrifice", AL["First Aid"] },
		{ 13, "SurvivalApprentice1", "Trade_Survival", AL["Survival"] },
		{ 14, "Gardening1", "Trade_Herbalism", AL["Gardening"] },
		{ 15, "Poisons1", "Trade_BrewPoison", AL["Poisons"] },
		{ 16, "CRAFTSET", "INV_Pants_Wolf", AL["Crafted Sets"] },
		{ 17, "CraftedWeapons1", "INV_Hammer_Unique_Sulfuras", AL["Crafted Epic Weapons"] },
    },
    ALCHEMYMENU = {
        { 1, "AlchemyApprentice1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Apprentice"] },
        { 2, "AlchemyJourneyman1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Journeyman"] },
        { 3, "AlchemyExpert1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Expert"] },
        { 4, "AlchemyArtisan1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Artisan"] },
        { 6, "AlchemyFlasks1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Flasks"] },
        { 7, "AlchemyProtectionPots1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Protection Potions"] },
        { 8, "AlchemyHealingAndMana1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Health and Mana Potions"] },
        { 9, "AlchemyTransmutes1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Transmutes"] },
        { 10, "AlchemyDefensive1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Defensive Potions and Elixirs"] },
        { 11, "AlchemyOffensive1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Offensive Potions and Elixirs"] },
        { 12, "AlchemyMisc1", "Trade_Alchemy", AL["Alchemy"]..": "..AL["Miscellaneous"] },
    },
    SMITHINGMENU = {
        { 1, "SmithingApprentice1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Apprentice"] },
        { 2, "SmithingJourneyman1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Journeyman"] },
        { 3, "SmithingExpert1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Expert"] },
        { 4, "SmithingArtisan1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Artisan"] },
        { 6, "SmithingHelm1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Helm"] },
        { 7, "SmithingShoulders1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Shoulders"] },
        { 8, "SmithingChest1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Chest"] },
        { 9, "SmithingBracers1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Bracers"] },
        { 10, "SmithingGloves1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Gloves"] },
        { 11, "SmithingBelt1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Belt"] },
        { 12, "SmithingPants1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Pants"] },
        { 13, "SmithingBoots1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Boots"] },
        { 14, "SmithingBuckles1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Belt Buckles"] },
        { 16, "SmithingAxes1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Axes"] },
        { 17, "SmithingSwords1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Swords"] },
        { 18, "SmithingMaces1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Maces"] },
        { 19, "SmithingFist1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Fist"] },
        { 20, "SmithingDaggers1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Daggers"] },
        { 21, "SmithingMisc1", "Trade_BlackSmithing", AL["Blacksmithing"]..": "..AL["Misc"] },
        { 23, "Armorsmith1", "INV_Chest_Plate04", AL["Armorsmith"] },
        { 24, "Weaponsmith1", "INV_Sword_25", AL["Weaponsmith"] },
        { 25, "Axesmith1", "INV_Axe_05", AL["Master Axesmith"] },
        { 26, "Hammersmith1", "INV_Hammer_23", AL["Master Hammersmith"] },
        { 27, "Swordsmith1", "INV_Sword_41", AL["Master Swordsmith"] },
    },
    ENCHANTINGMENU = {
		{ 1, "EnchantingApprentice1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Apprentice"] },
		{ 2, "EnchantingJourneyman1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Journeyman"] },
		{ 3, "EnchantingExpert1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Expert"] },
		{ 4, "EnchantingArtisan1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Artisan"] },
		{ 6, "EnchantingCloak1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Cloak"] },
		{ 7, "EnchantingChest1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Chest"] },
		{ 8, "EnchantingBracer1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Bracers"] },
		{ 9, "EnchantingGlove1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Gloves"] },
		{ 10, "EnchantingBoots1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Boots"] },
		{ 11, "Enchanting2HWeapon1", "Trade_Engraving", AL["Enchanting"]..": "..AL["2H Weapon"] },
		{ 12, "EnchantingWeapon1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Weapon"] },
		{ 13, "EnchantingShield1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Shield"] },
		{ 14, "EnchantingMisc1", "Trade_Engraving", AL["Enchanting"]..": "..AL["Misc"] },
    },
    ENGINEERINGMENU = {
		{ 1, "EngineeringApprentice1", "Trade_Engineering", AL["Engineering"]..": "..AL["Apprentice"] },
		{ 2, "EngineeringJourneyman1", "Trade_Engineering", AL["Engineering"]..": "..AL["Journeyman"] },
		{ 3, "EngineeringExpert1", "Trade_Engineering", AL["Engineering"]..": "..AL["Expert"] },
		{ 4, "EngineeringArtisan1", "Trade_Engineering", AL["Engineering"]..": "..AL["Artisan"] },
		{ 6, "EngineeringEquipment1", "Trade_Engineering", AL["Engineering"]..": "..AL["Equipment"] },
		{ 7, "EngineeringTrinkets1", "Trade_Engineering", AL["Engineering"]..": "..AL["Trinkets"] },
		{ 8, "EngineeringExplosives1", "Trade_Engineering", AL["Engineering"]..": "..AL["Explosives"] },
		{ 9, "EngineeringWeapons1", "Trade_Engineering", AL["Engineering"]..": "..AL["Weapons"] },
		{ 10, "EngineeringParts1", "Trade_Engineering", AL["Engineering"]..": "..AL["Parts"] },
		{ 11, "EngineeringMisc1", "Trade_Engineering", AL["Engineering"]..": "..AL["Misc"] },
		{ 13, "Gnomish1", "Trade_Engineering", AL["Gnomish Engineering"] },
		{ 14, "Goblin1", "Trade_Engineering", AL["Goblin Engineering"] },
    },
    LEATHERWORKINGMENU = {
		{ 1, "LeatherApprentice1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Apprentice"] },
		{ 2, "LeatherJourneyman1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Journeyman"] },
		{ 3, "LeatherExpert1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Expert"] },
		{ 4, "LeatherArtisan1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Artisan"] },
		{ 6, "LeatherHelm1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Helm"] },
		{ 7, "LeatherShoulders1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Shoulders"] },
		{ 8, "LeatherCloak1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Cloak"] },
		{ 9, "LeatherChest1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Chest"] },
		{ 10, "LeatherBracers1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Bracers"] },
		{ 11, "LeatherGloves1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Gloves"] },
		{ 12, "LeatherBelt1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Belt"] },
		{ 13, "LeatherPants1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Pants"] },
		{ 14, "LeatherBoots1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Boots"] },
		{ 15, "LeatherBags1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Bags"] },
		{ 16, "LeatherMisc1", "INV_Misc_ArmorKit_17", AL["Leatherworking"]..": "..AL["Misc"] },
		{ 18, "Dragonscale1", "INV_Misc_MonsterScales_03", AL["Dragonscale Leatherworking"] },
		{ 19, "Elemental1", "Spell_Fire_Volcano", AL["Elemental Leatherworking"] },
		{ 20, "Tribal1", "Spell_Nature_NullWard", AL["Tribal Leatherworking"] },
    },
    TAILORINGMENU = {
		{ 1, "TailoringApprentice1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Apprentice"] },
		{ 2, "TailoringJourneyman1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Journeyman"] },
		{ 3, "TailoringExpert1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Expert"] },
		{ 4, "TailoringArtisan1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Artisan"] },
		{ 6, "TailoringHelm1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Helm"] },
		{ 7, "TailoringShoulders1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Shoulders"] },
		{ 8, "TailoringCloak1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Cloak"] },
		{ 9, "TailoringChest1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Chest"] },
		{ 10, "TailoringBracers1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Bracers"] },
		{ 11, "TailoringGloves1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Gloves"] },
		{ 12, "TailoringBelt1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Belt"] },
		{ 13, "TailoringPants1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Pants"] },
		{ 14, "TailoringBoots1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Boots"] },
		{ 15, "TailoringShirt1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Shirt"] },
		{ 16, "TailoringBags1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Bags"] },
		{ 17, "TailoringMisc1", "Trade_Tailoring", AL["Tailoring"]..": "..AL["Misc"] },
    },
    JEWELCRAFTMENU = {
		{ 1, "JewelcraftingApprentice1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Apprentice"] },
		{ 2, "JewelcraftingJourneyman1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Journeyman"] },
		{ 3, "JewelcraftingExpert1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Expert"] },
		{ 4, "JewelcraftingArtisan1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Artisan"] },
		{ 6, "JewelcraftingGemstones1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Gemstones"] },
		{ 7, "JewelcraftingRings1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Rings"] },
		{ 8, "JewelcraftingAmulets1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Amulets"] },
		{ 9, "JewelcraftingHelm1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Head"] },
		{ 10, "JewelcraftingBracers1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Bracers"] },
		{ 11, "JewelcraftingOffHands1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Off Hand"] },
		{ 12, "JewelcraftingStaves1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Staff"] },
		{ 13, "JewelcraftingTrinkets1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Trinkets"] },
		{ 14, "JewelcraftingMisc1", "INV_Jewelry_Necklace_01", AL["Jewelcrafting"]..": "..AL["Misc"] },
		{ 16, "JewelcraftingGemology1", "INV_Misc_Gem_Variety_01", AL["Jewelcrafting"]..": "..AL["Gemology"] },
		{ 17, "JewelcraftingGoldsmithing1", "INV_Jewelry_Ring_03", AL["Jewelcrafting"]..": "..AL["Goldsmithing"] },
    },
    CRAFTSET = {
        { 1, nil, "INV_Helmet_11", AL["Augerer's Attire"], "", AtlasLoot_Data.AtlasLootCrafting.AugerersAttireC },
        { 2, nil, "INV_Helmet_27", AL["Shadoweave"], "", AtlasLoot_Data.AtlasLootCrafting.ShadoweaveSetC },
        { 3, nil, "INV_Helmet_33", AL["Diviner's Garments"], "", AtlasLoot_Data.AtlasLootCrafting.DivinersGarmentsC },
        { 4, nil, "INV_Helmet_28", AL["Pillager's Garb"], "", AtlasLoot_Data.AtlasLootCrafting.PillagersGarbC },
        { 5, nil, "INV_Pants_Cloth_14", AL["Bloodvine Garb"], "", AtlasLoot_Data.AtlasLootCrafting.BloodvineGC },
        { 6, nil, "inv_chest_cloth_08", AL["Mooncloth Regalia"], "", AtlasLoot_Data.AtlasLootCrafting.MoonclothSetC },
        { 8, nil, "INV_Shoulder_15", AL["Bloodsoul Embrace"], "", AtlasLoot_Data.AtlasLootCrafting.BloodsoulEmbraceC },
        { 9, nil, "INV_Helmet_25", AL["Steel Plate"], "", AtlasLoot_Data.AtlasLootCrafting.SteelPlateC },
        { 10, nil, "INV_Belt_01", AL["Imperial Plate"], "", AtlasLoot_Data.AtlasLootCrafting.ImperialPlateC },
        { 11, nil, "INV_Shoulder_01", AL["The Darksoul"], "", AtlasLoot_Data.AtlasLootCrafting.TheDarksoulC },
        { 13, nil, "INV_Helmet_33", AL["Grifter's Armor"], "", AtlasLoot_Data.AtlasLootCrafting.GriftersArmorC },
        { 14, nil, "INV_Helmet_04", AL["Primalist's Trappings"], "", AtlasLoot_Data.AtlasLootCrafting.PrimalistsTrappingsC },
        { 15, nil, "INV_Pants_06", AL["Volcanic Armor"], "", AtlasLoot_Data.AtlasLootCrafting.VolcanicArmorC },
        { 16, nil, "INV_Chest_Leather_06", AL["Ironfeather Armor"], "", AtlasLoot_Data.AtlasLootCrafting.IronfeatherArmorC },
        { 17, nil, "INV_Chest_Leather_08", AL["Stormshroud Armor"], "", AtlasLoot_Data.AtlasLootCrafting.StormshroudArmorC },
        { 18, nil, "INV_Pants_Wolf", AL["Devilsaur Armor"], "", AtlasLoot_Data.AtlasLootCrafting.DevilsaurArmorC },
        { 19, nil, "INV_Shoulder_23", AL["Blood Tiger Harness"], "", AtlasLoot_Data.AtlasLootCrafting.BloodTigerHC },
        { 20, nil, "INV_Chest_Leather_03", AL["Primal Batskin"], "", AtlasLoot_Data.AtlasLootCrafting.PrimalBatskinC },
        { 22, nil, "inv_chest_chain_06", AL["Red Dragon Mail"], "", AtlasLoot_Data.AtlasLootCrafting.RedDragonMC },
        { 23, nil, "INV_Pants_05", AL["Green Dragon Mail"], "", AtlasLoot_Data.AtlasLootCrafting.GreenDragonMC },
        { 24, nil, "INV_Chest_Chain_04", AL["Blue Dragon Mail"], "", AtlasLoot_Data.AtlasLootCrafting.BlueDragonMC },
        { 25, nil, "INV_Pants_03", AL["Black Dragon Mail"], "", AtlasLoot_Data.AtlasLootCrafting.BlackDragonMC },
    },

    -- World bosses
    WORLDBOSSMENU = {
        { 1, "AAzuregos", "INV_Misc_Head_Dragon_Blue", AL["Azuregos"], ORANGE..AL["Azshara"] },
        { 2, "DEmeriss", "INV_Misc_Head_Dragon_Green", AL["Emeriss"], ORANGE..AL["Various Locations"] },
        { 3, "DLethon", "INV_Misc_Head_Dragon_Green", AL["Lethon"], ORANGE..AL["Various Locations"] },
        { 4, "DTaerar", "INV_Misc_Head_Dragon_Green", AL["Taerar"], ORANGE..AL["Various Locations"] },
        { 5, "DYsondre", "INV_Misc_Head_Dragon_Green", AL["Ysondre"], ORANGE..AL["Various Locations"] },
        { 6, "KKazzak", "warlock_summon_doomguard", AL["Lord Kazzak"], ORANGE..AL["Blasted Lands"] },
        { 7, "Nerubian", "Spell_Nature_Web", AL["Nerubian Overseer"], ORANGE..AL["Eastern Plaguelands"] },
        { 8, "Reaver", "Ability_Mount_Dreadsteed", AL["Dark Reaver of Karazhan"], ORANGE..AL["Deadwind Pass"] },
        { 9, "Ostarius", "INV_Misc_Platnumdisks", AL["Ostarius"], ORANGE..AL["Tanaris"] },
        { 10, "Concavius", "Spell_Shadow_SummonVoidWalker", AL["Concavius"], ORANGE..AL["Desolace"] },
        { 11, "CowKing", "Spell_Nature_Polymorph_Cow", AL["Moo"], ORANGE..AL["Moomoo Grove"] },
        { 12, "Clackora", "INV_Misc_Birdbeck_02", AL["Cla'ckora"], ORANGE..AL["Azshara"] },
    },

    -- Events
    WORLDEVENTMENU = {
        { 1, "AbyssalTemplars", "INV_Staff_13", AL["Abyssal Council"], ORANGE..AL["Silithus"] },
        { 2, "ElementalInvasion", "Spell_Fire_Elemental_Totem", AL["Elemental Invasion"], ORANGE..AL["Various Locations"] },
        { 3, "ChildrensWeek", "Ability_Hunter_BeastCall", AL["Children's Week"], ORANGE..AL["Various Locations"] },
        { 4, "Winterviel1", "INV_Holiday_Christmas_Present_01", AL["Feast of Winter Veil"], ORANGE..AL["Various Locations"] },
        { 5, "Halloween1", "INV_Misc_Food_59", AL["Hallow's End"], ORANGE..AL["Various Locations"] },
        { 6, "HarvestFestival", "INV_Misc_Food_Wheat_01", AL["Harvest Festival"], ORANGE..AL["Various Locations"] },
        { 7, "Valentineday", "INV_ValentinesBoxOfChocolates02", AL["Love is in the Air"], ORANGE..AL["Various Locations"] },
        { 8, "LunarFestival1", "INV_Misc_ElvenCoins", AL["Lunar Festival"], ORANGE..AL["Various Locations"] },
        { 9, "MidsummerFestival", "INV_SummerFest_Symbol_Medium", AL["Midsummer Fire Festival"], ORANGE..AL["Various Locations"] },
        { 10, "Noblegarden", "INV_Egg_03", AL["Noblegarden"], ORANGE..AL["Various Locations"] },
        { 11, "GurubashiArena", "INV_Misc_ArmorKit_04", AL["Gurubashi Arena"], ORANGE..AL["Stranglethorn Vale"] },
        { 12, "ScourgeInvasionEvent1", "INV_Jewelry_Talisman_13", AL["Scourge Invasion"], ORANGE..AL["Various Locations"] },
        { 13, "FishingExtravaganza", "INV_Fishingpole_01", AL["Stranglethorn Fishing Extravaganza"], ORANGE..AL["Stranglethorn Vale"] },
    },

    -- Dungeons
    DUNGEONSMENU1 = {
		{ 1, "RFCTaragaman", "Spell_Arcane_PortalIronForge", WHITE.."[13-18]|r "..AL["Ragefire Chasm"], ORANGE..AL["Orgrimmar"] },
		{ 2, "FMHTansha", "Spell_Arcane_PortalIronForge", WHITE.."[13-20]|r "..AL["Frostmane Hollow"], ORANGE..AL["Dun Morogh"] },
		{ 3, "WCLordCobrahn", "Spell_Arcane_PortalIronForge", WHITE.."[17-24]|r "..AL["Wailing Caverns"], ORANGE..AL["Barrens"] },
		{ 4, "DMRhahkZor", "Spell_Arcane_PortalIronForge", WHITE.."[17-24]|r "..AL["The Deadmines"], ORANGE..AL["Westfall"] },
		{ 5, "SFKRethilgore", "Spell_Arcane_PortalIronForge", WHITE.."[22-30]|r "..AL["Shadowfang Keep"], ORANGE..AL["Silverpine Forest"] },
		{ 6, "SWStTargorr", "Spell_Arcane_PortalIronForge", WHITE.."[22-30]|r "..AL["The Stockade"], ORANGE..AL["Stormwind"] },
		{ 7, "BFDGhamoora", "Spell_Arcane_PortalIronForge", WHITE.."[23-32]|r "..AL["Blackfathom Deeps"], ORANGE..AL["Ashenvale"] },
		{ 8, "WHCPathun", "Spell_Arcane_PortalIronForge", WHITE.."[25-33]|r "..AL["Windhorn Canyon"], ORANGE..AL["Thousand Needles"] },
		{ 9, "DMRGowlfang", "Spell_Arcane_PortalIronForge", WHITE.."[26-35]|r "..AL["Dragonmaw Retreat"], ORANGE..AL["Wetlands"] },
		{ 10, "GnGrubbis", "Spell_Arcane_PortalIronForge", WHITE.."[29-38]|r "..AL["Gnomeregan"], ORANGE..AL["Dun Morogh"] },
		{ 11, "RFKAggem", "Spell_Arcane_PortalIronForge", WHITE.."[29-38]|r "..AL["Razorfen Kraul"], ORANGE..AL["Barrens"] },
		{ 12, "TCGGrovetenderEngryss", "Spell_Arcane_PortalIronForge", WHITE.."[32-38]|r "..AL["The Crescent Grove"], ORANGE..AL["Ashenvale"] },
		{ 13, "SMVishas", "Spell_Arcane_PortalIronForge", WHITE.."[27-36]|r "..AL["Scarlet Monastery (Graveyard)"], ORANGE..AL["Tirisfal Glades"] },
		{ 14, "SMHoundmasterLoksey", "Spell_Arcane_PortalIronForge", WHITE.."[28-39]|r "..AL["Scarlet Monastery (Library)"], ORANGE..AL["Tirisfal Glades"] },
		{ 15, "SMHerod", "Spell_Arcane_PortalIronForge", WHITE.."[32-41]|r "..AL["Scarlet Monastery (Armory)"], ORANGE..AL["Tirisfal Glades"] },
		{ 16, "SMFairbanks", "Spell_Arcane_PortalIronForge", WHITE.."[35-45]|r "..AL["Scarlet Monastery (Cathedral)"], ORANGE..AL["Tirisfal Glades"] },
		{ 17, "SWROronok", "Spell_Arcane_PortalIronForge", WHITE.."[32-44]|r "..AL["Stormwrought Ruins"], ORANGE..AL["Balor"] },
		{ 18, "RFDTutenkash", "Spell_Arcane_PortalIronForge", WHITE.."[36-46]|r "..AL["Razorfen Downs"], ORANGE..AL["Barrens"] },
		{ 19, "UldBaelog", "Spell_Arcane_PortalIronForge", WHITE.."[40-51]|r "..AL["Uldaman"], ORANGE..AL["Badlands"] },
		{ 20, "GCMatthiasHoltz", "Spell_Arcane_PortalIronForge", WHITE.."[42-50]|r "..AL["Gilneas City"], ORANGE..AL["Gilneas"] },
		{ 21, "MaraNoxxion", "Spell_Arcane_PortalIronForge", WHITE.."[45-55]|r "..AL["Maraudon"], ORANGE..AL["Desolace"] },
		{ 22, "ZFAntusul", "Spell_Arcane_PortalIronForge", WHITE.."[44-54]|r "..AL["Zul'Farrak"], ORANGE..AL["Tanaris"] },
		{ 23, "STBalconyMinibosses", "Spell_Arcane_PortalIronForge", WHITE.."[50-60]|r "..AL["The Sunken Temple"], ORANGE..AL["Swamp of Sorrows"] },
		{ 24, "HQHighForemanBargulBlackhammer", "Spell_Arcane_PortalIronForge", WHITE.."[50-60]|r "..AL["Hateforge Quarry"], ORANGE..AL["Burning Steppes"] },
		{ 25, "BRDLordRoccor", "Spell_Arcane_PortalIronForge", WHITE.."[52-60]|r "..AL["Blackrock Depths"], ORANGE..AL["Burning Steppes"] },
		{ 26, "DMEPusillin", "Spell_Arcane_PortalIronForge", WHITE.."[55-60]|r "..AL["Dire Maul (East)"], ORANGE..AL["Feralas"] },
		{ 27, "DMWTendrisWarpwood", "Spell_Arcane_PortalIronForge", WHITE.."[57-60]|r "..AL["Dire Maul (West)"], ORANGE..AL["Feralas"] },
		{ 28, "DMNGuardMoldar", "Spell_Arcane_PortalIronForge", WHITE.."[57-60]|r "..AL["Dire Maul (North)"], ORANGE..AL["Feralas"] },
		{ 29, "SCHOLOKirtonostheHerald", "Spell_Arcane_PortalIronForge", WHITE.."[58-60]|r "..AL["Scholomance"], ORANGE..AL["Western Plaguelands"] },
		{ 30, "STRATSkull", "Spell_Arcane_PortalIronForge", WHITE.."[58-60]|r "..AL["Stratholme"], ORANGE..AL["Eastern Plaguelands"] },
    },
    DUNGEONSMENU2 = {
		{ 1, "LBRSSpirestoneButcher", "Spell_Arcane_PortalIronForge", WHITE.."[55-60]|r "..AL["Lower Blackrock Spire"], ORANGE..AL["Burning Steppes"] },
		{ 2, "UBRSEmberseer", "Spell_Arcane_PortalIronForge", WHITE.."[58-60]|r "..AL["Upper Blackrock Spire"], ORANGE..AL["Burning Steppes"] },
		{ 3, "COTBMChronar", "Spell_Arcane_PortalIronForge", WHITE.."[60]|r "..AL["Caverns of Time: Black Morass"], ORANGE..AL["Tanaris"] },
		{ 4, "SWVAszoshGrimflame", "Spell_Arcane_PortalIronForge", WHITE.."[60]|r "..AL["Stormwind Vault"], ORANGE..AL["Stormwind"] },
		{ 5, "KCMarrowspike", "Spell_Arcane_PortalIronForge", WHITE.."[60]|r "..AL["Karazhan Crypt"], ORANGE..AL["Deadwind Pass"] },
		{ 7, "ZGJeklik", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Zul'Gurub"], ORANGE..AL["Stranglethorn Vale"] },
		{ 8, "AQ20Kurinnaxx", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Ruins of Ahn'Qiraj"], ORANGE..AL["Silithus"] },
		{ 9, "Axelus", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Onyxia's Lair"], ORANGE..AL["Dustwallow Marsh"] },
		{ 10, "MCIncindis", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Molten Core"], ORANGE..AL["Burning Steppes"] },
		{ 11, "LKHRolfen", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Lower Karazhan Halls"], ORANGE..AL["Deadwind Pass"] },
		{ 12, "BWLRazorgore", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Blackwing Lair"], ORANGE..AL["Burning Steppes"] },
		{ 13, "ESErennius", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Emerald Sanctum"], ORANGE..AL["Hyjal"] },
		{ 14, "TMHKarrsh", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Timbermaw Hold"], ORANGE..AL["Azshara"] },
		{ 15, "AQ40Skeram", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Temple of Ahn'Qiraj"], ORANGE..AL["Silithus"] },
		{ 16, "NAXPatchwerk", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Naxxramas"], ORANGE..AL["Eastern Plaguelands"] },
		{ 17, "UKHGnarlmoon", "Spell_Arcane_PortalOrgrimmar", RED.."[RAID]|r "..AL["Upper Karazhan Halls"], ORANGE..AL["Deadwind Pass"] },
    },
}


-- This is a multi-layer table defining the main loot listing.
-- Entries have the text to display, loot table or sub table to link to and if the link is to a loot table or sub table
AtlasLoot_HewdropDown = {
	{
		[AL["Dungeons & Raids"]] = {
			{ { WHITE.."[13-18]|r "..AL["Ragefire Chasm"], "RagefireChasm", "Submenu" }, },
			{ { WHITE.."[13-20]|r "..AL["Frostmane Hollow"], "FrostmaneHollow", "Submenu" }, },
			{ { WHITE.."[17-24]|r "..AL["Wailing Caverns"], "WailingCaverns", "Submenu" }, },
			{ { WHITE.."[17-24]|r "..AL["The Deadmines"], "Deadmines", "Submenu" }, },
			{ { WHITE.."[22-30]|r "..AL["Shadowfang Keep"], "ShadowfangKeep", "Submenu" }, },
			{ { WHITE.."[23-32]|r "..AL["Blackfathom Deeps"], "BlackfathomDeeps", "Submenu" }, },
			{ { WHITE.."[25-33]|r "..AL["Windhorn Canyon"], "WindhornCanyon", "Submenu" }, },
			{ { WHITE.."[22-30]|r "..AL["The Stockade"], "TheStockade", "Submenu" }, },
			{ { WHITE.."[26-35]|r "..AL["Dragonmaw Retreat"], "DragonmawRetreat", "Submenu" }, },
			{ { WHITE.."[29-38]|r "..AL["Gnomeregan"], "Gnomeregan", "Submenu" }, },
			{ { WHITE.."[29-38]|r "..AL["Razorfen Kraul"], "RazorfenKraul", "Submenu" }, },
			{ { WHITE.."[32-38]|r "..AL["The Crescent Grove"], "TheCrescentGrove", "Submenu" }, },
			{
				[WHITE.."[27-45]|r "..AL["Scarlet Monastery"]] = {
					{ WHITE.."[27-36]|r "..AL["Scarlet Monastery (Graveyard)"], "SMGraveyard", "Submenu" },
					{ WHITE.."[28-39]|r "..AL["Scarlet Monastery (Library)"], "SMLibrary", "Submenu" },
					{ WHITE.."[32-41]|r "..AL["Scarlet Monastery (Armory)"], "SMArmory", "Submenu" },
					{ WHITE.."[35-45]|r "..AL["Scarlet Monastery (Cathedral)"], "SMCathedral", "Submenu" },
				},
			},
			{ { WHITE.."[32-44]|r "..AL["Stormwrought Ruins"], "StormwroughtRuins", "Submenu" }, },
			{ { WHITE.."[36-46]|r "..AL["Razorfen Downs"], "RazorfenDowns", "Submenu" }, },
			{ { WHITE.."[40-51]|r "..AL["Uldaman"], "Uldaman", "Submenu" }, },
			{ { WHITE.."[42-50]|r "..AL["Gilneas City"], "GilneasCity", "Submenu" }, },
			{ { WHITE.."[45-55]|r "..AL["Maraudon"], "Maraudon", "Submenu" }, },
			{ { WHITE.."[44-54]|r "..AL["Zul'Farrak"], "ZulFarrak", "Submenu" }, },
			{ { WHITE.."[50-60]|r "..AL["The Sunken Temple"], "SunkenTemple", "Submenu" }, },
			{ { WHITE.."[50-60]|r "..AL["Hateforge Quarry"], "HateforgeQuarry", "Submenu" }, },
			{ { WHITE.."[52-60]|r "..AL["Blackrock Depths"], "BlackrockDepths", "Submenu" }, },
			{
				[WHITE.."[55-60]|r "..AL["Dire Maul"]] = {
					{ WHITE.."[55-60]|r "..AL["Dire Maul (East)"], "DireMaulEast", "Submenu" },
					{ WHITE.."[57-60]|r "..AL["Dire Maul (West)"], "DireMaulWest", "Submenu" },
					{ WHITE.."[57-60]|r "..AL["Dire Maul (North)"], "DireMaulNorth", "Submenu" },
				},
			},
			{ { WHITE.."[58-60]|r "..AL["Scholomance"], "Scholomance", "Submenu" }, },
			{ { WHITE.."[58-60]|r "..AL["Stratholme"], "Stratholme", "Submenu" }, },
			{ { WHITE.."[55-60]|r "..AL["Lower Blackrock Spire"], "LowerBlackrock", "Submenu" }, },
			{ { WHITE.."[58-60]|r "..AL["Upper Blackrock Spire"], "UpperBlackrock", "Submenu" }, },
			{ { WHITE.."[58-60]|r "..AL["Karazhan Crypt"], "KarazhanCrypt", "Submenu" }, },
			{ { WHITE.."[60]|r "..AL["Caverns of Time: Black Morass"], "CavernsOfTimeBlackMorass", "Submenu" }, },
			{ { WHITE.."[60]|r "..AL["Stormwind Vault"], "StormwindVault", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Zul'Gurub"], "ZulGurub", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Ruins of Ahn'Qiraj"], "RuinsofAQ", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Molten Core"], "MoltenCore", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Onyxia's Lair"], "Onyxia", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Lower Karazhan Halls"], "LowerKara", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Blackwing Lair"], "BlackwingLair", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Emerald Sanctum"], "EmeraldSanctum", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Timbermaw Hold"], "TimbermawHold", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Temple of Ahn'Qiraj"], "TempleofAQ", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Naxxramas"], "Naxxramas", "Submenu" }, },
			{ { RED.."[RAID]|r "..AL["Upper Karazhan Halls"], "UpperKara", "Submenu" }, },
		},
	},
	{
		[AL["World Bosses"]] = {
			{ { AL["Azuregos"], "AAzuregos", "Table" }, },
			{ { AL["Emeriss"], "DEmeriss", "Table" }, },
			{ { AL["Lethon"], "DLethon", "Table" }, },
			{ { AL["Taerar"], "DTaerar", "Table" }, },
			{ { AL["Ysondre"], "DYsondre", "Table" }, },
			{ { AL["Lord Kazzak"], "KKazzak", "Table" }, },
			{ { AL["Nerubian Overseer"], "Nerubian", "Table" }, },
			{ { AL["Dark Reaver of Karazhan"], "Reaver", "Table" }, },
			{ { AL["Ostarius"], "Ostarius", "Table" }, },
			{ { AL["Concavius"], "Concavius", "Table" }, },
			{ { AL["Moo"], "CowKing", "Table" }, },
			{ { AL["Cla'ckora"], "Clackora", "Table" }, },
		},
	},
	{
		[AL["PvP Rewards"]] = {
			{ { AL["PvP Armor Sets"], "PVPSET", "Table" }, },
			{ { AL["PvP Accessories"], "PvP60Accessories1", "Table" }, },
			{ { AL["Rank 14 Weapons"], "PVPWeapons1", "Table" }, },
			{ { AL["PvP Mounts"], "PvPMountsPvP", "Table" }, },
			{ { AL["Blood Ring"], "BRRepMenu", "Table" }, },
			{ { AL["Alterac Valley"], "AVRepMenu", "Table" }, },
			{ { AL["Arathi Basin"], "ABRepMenu", "Table" }, },
			{ { AL["Warsong Gulch"], "WSGRepMenu", "Table" }, },
		},
	},
	{
		[AL["Collections"]] = {
			{ { AL["Sets"], "PRE60SET", "Table" }, },
			{ { AL["Zul'Gurub Sets"], "ZGSET", "Table" }, },
			{ { AL["Ruins of Ahn'Qiraj Sets"], "AQ20SET", "Table" }, },
			{ { AL["Temple of Ahn'Qiraj Sets"], "AQ40SET", "Table" }, },
			{ { AL["Karazhan Sets"], "KARASET", "Table" }, },
			{ { AL["Dungeon Sets"], "T0SET", "Table" }, },
			{ { AL["Tier 1 Sets"], "T1SET", "Table" }, },
			{ { AL["Tier 2 Sets"], "T2SET", "Table" }, },
			{ { AL["Tier 3 Sets"], "T3SET", "Table" }, },
			{ { AL["Legendary Items"], "Legendaries", "Table" }, },
			{ { AL["World Epics"], "WorldEpics1", "Table" }, },
			{ { AL["Rare Pets"], "RarePets1", "Table" }, },
			{ { AL["Rare Mounts"], "RareMounts", "Table" }, },
			{ { AL["Tabards"], "Tabards", "Table" }, },
		},
	},
	{
		[AL["Factions"]] = {
			{ { AL["Argent Dawn"], "Argent1", "Table" }, },
			{ { AL["Brood of Nozdormu"], "AQBroodRings", "Table" }, },
			{ { AL["Darkmoon Faire"], "Darkmoon", "Table" }, },
			{ { AL["Hydraxian Waterlords"], "WaterLords1", "Table" }, },
			{ { AL["Thorium Brotherhood"], "Thorium1", "Table" }, },
			{ { AL["Cenarion Circle"], "Cenarion1", "Table" } },
			{ { AL["Shen'dralar"], "Shendralar", "Table" }, },
			{ { AL["Draenei Exiles"], "DraeneiExiles", "Table" }, },
			{ { AL["Bloodsail Buccaneers"], "Bloodsail1", "Table" }, },
			{ { AL["Zandalar Tribe"], "Zandalar1", "Table" }, },
			{ { AL["Timbermaw Hold"], "Timbermaw", "Table" }, },
			{ { AL["Wardens of Time"], "Wardens1", "Table" }, },
			{ { AL["Gelkis Clan Centaur"], "GelkisClan1", "Table" }, },
			{ { AL["Magram Clan Centaur"], "MagramClan1", "Table" }, },
			{ { BLUE.."["..AL["Alliance"].."]|r "..AL["Stormwind"], "Stormwind", "Table" }, },
			{ { BLUE.."["..AL["Alliance"].."]|r "..AL["Ironforge"], "Ironforge", "Table" }, },
			{ { BLUE.."["..AL["Alliance"].."]|r "..AL["Gnomeregan Exiles"], "GnomereganExiles", "Table" }, },
			{ { BLUE.."["..AL["Alliance"].."]|r "..AL["Darnassus"], "Darnassus", "Table" }, },
			{ { BLUE.."["..AL["Alliance"].."]|r "..AL["Silvermoon Remnant"], "Helf", "Table" }, },
			{ { BLUE.."["..AL["Alliance"].."]|r "..AL["Dalaran"], "Dalaran", "Table" }, },
			{ { BLUE.."["..AL["Alliance"].."]|r "..AL["Wintersaber Trainers"], "Wintersaber1", "Table" }, },
			{ { BLUE.."["..AL["Alliance"].."]|r "..AL["Wildhammer Clan"], "Wildhammer", "Table" }, },
			{ { RED.."["..AL["Horde"].."]|r "..AL["Orgrimmar"], "Orgrimmar", "Table" }, },
			{ { RED.."["..AL["Horde"].."]|r "..AL["Darkspear Trolls"], "DarkspearTrolls", "Table" }, },
			{ { RED.."["..AL["Horde"].."]|r "..AL["Thunder Bluff"], "ThunderBluff", "Table" }, },
			{ { RED.."["..AL["Horde"].."]|r "..AL["Undercity"], "Undercity", "Table" }, },
			{ { RED.."["..AL["Horde"].."]|r "..AL["Durotar Labor Union"], "DurotarLaborUnion", "Table" }, },
			{ { RED.."["..AL["Horde"].."]|r "..AL["Revantusk Trolls"], "Revantusk", "Table" }, },
			{ { RED.."["..AL["Horde"].."]|r "..AL["Earthen Ring"], "EarthenRing", "Table" }, },
		},
	},
	{
		[AL["World Events"]] = {
			{ { AL["Abyssal Council"], "AbyssalTemplars", "Table" }, },
			{ { AL["Children's Week"], "ChildrensWeek", "Table" }, },
			{ { AL["Elemental Invasion"], "ElementalInvasion", "Table" }, },
			{ { AL["Feast of Winter Veil"], "Winterviel1", "Table" }, },
			{ { AL["Gurubashi Arena"], "GurubashiArena", "Table" }, },
			{ { AL["Hallow's End"], "Halloween1", "Table" }, },
			{ { AL["Harvest Festival"], "HarvestFestival", "Table" }, },
			{ { AL["Love is in the Air"], "Valentineday", "Table" }, },
			{ { AL["Lunar Festival"], "LunarFestival1", "Table" }, },
			{ { AL["Midsummer Fire Festival"], "MidsummerFestival", "Table" }, },
			{ { AL["Noblegarden"], "Noblegarden", "Table" }, },
			{ { AL["Scourge Invasion"], "ScourgeInvasionEvent1", "Table" }, },
			{ { AL["Stranglethorn Fishing Extravaganza"], "FishingExtravaganza", "Table" }, },
		},
	},
	{
		[AL["Crafting"]] = {
			{ { AL["Alchemy"], "ALCHEMYMENU", "Table" }, },
			{ { AL["Blacksmithing"], "SMITHINGMENU", "Table" }, },
			{ { AL["Enchanting"], "ENCHANTINGMENU", "Table" }, },
			{ { AL["Engineering"], "ENGINEERINGMENU", "Table" }, },
			{ { AL["Herbalism"], "Herbalism1", "Table" }, },
			{ { AL["Leatherworking"], "LEATHERWORKINGMENU", "Table" }, },
			{ { AL["Jewelcrafting"], "JEWELCRAFTMENU", "Table" }, },
			{ { AL["Mining"], "Mining1", "Table" }, },
			{ { AL["Tailoring"], "TAILORINGMENU", "Table" }, },
			{ { AL["Cooking"], "CookingApprentice1", "Table" }, },
			{ { AL["First Aid"], "FirstAid1", "Table" }, },
			{ { AL["Survival"], "SurvivalApprentice1", "Table" }, },
			{ { AL["Gardening"], "Gardening1", "Table" }, },
			{ { AL["Poisons"], "Poisons1", "Table" }, },
			{ { AL["Crafted Sets"], "CRAFTSET", "Table" }, },
			{ { AL["Crafted Epic Weapons"], "CraftedWeapons1", "Table" }, },
		},
	},
	{ { "Rare Spawns", "RareSpawns", "Submenu" }, },
}

-- This table defines all the subtables needed for the full menu
-- Each sub table entry contains the text entry and the loot table that goes wih it
AtlasLoot_HewdropDown_SubTables = {
	["FrostmaneHollow"] = {
		{ AL["Tan'sha the Sleek"], "FMHTansha" },
		{ AL["Kan'za the Seer"], "FMHKanza" },
		{ AL["Battlemaster Ubukaz"], "FMHBattlemaster" },
		{ AL["Hailar the Frigid"], "FMHHailar" },
	},
	["TimbermawHold"] = {
		{ AL["Karrsh the Sentinel"], "TMHKarrsh" },
		{ AL["Rotgrowl"], "TMHRotgrowl" },
		{ AL["Loktanag the Vile"], "TMHLoktanag" },
		{ AL["Ormanos the Cracked"], "TMHOrmanos" },
		{ AL["Chieftain Partath"], "TMHPartath" },
		{ AL["Archdruid Kronn"], "TMHKronn" },
		{ AL["Selenaxx Foulheart"], "TMHSelenaxx" },
		{ AL["Trioch the Devourer"], "TMHTrioch" },
		{ AL["Ursol"], "TMHUrsol" },
		{ AL["Peroth'arn"], "TMHPerotharn" },
	},
	["WindhornCanyon"] = {
		{ AL["Pathun Duskhide"], "WHCPathun" },
		{ AL["Ahgk'tos the Pure"], "WHCAhgktos" },
		{ AL["Ambassador Vortalus"], "WHCAmbassador" },
		{ AL["Walgan Bloodcaller"], "WHCWalgan" },
		{ AL["Bonespeaker Narlgom"], "WHCBonespeaker" },
		{ AL["Prophet Stormhoof"], "WHCProphet" },
		{ AL["Chieftain Shalk Blackwind"], "WHCChieftan" },
	},
	["HateforgeQuarry"] = {
		{ AL["High Foreman Bargul Blackhammer"], "HQHighForemanBargulBlackhammer" },
		{ AL["Engineer Figgles"], "HQEngineerFiggles" },
		{ AL["Corrosis"], "HQCorrosis" },
		{ AL["Hatereaver Annihilator"], "HQHatereaverAnnihilator" },
		{ AL["Har'gesh Doomcaller"], "HQHargeshDoomcaller" },
		{ AL["Trash Mobs"], "HQTrash" },
	},
	["BlackrockDepths"] = {
		{ AL["Lord Roccor"], "BRDLordRoccor" },
		{ AL["High Interrogator Gerstahn"], "BRDHighInterrogatorGerstahn" },
		{ AL["Anub'shiah"], "BRDAnubshiah" },
		{ AL["Eviscerator"], "BRDEviscerator" },
		{ AL["Gorosh the Dervish"], "BRDGorosh" },
		{ AL["Grizzle"], "BRDGrizzle" },
		{ AL["Hedrum the Creeper"], "BRDHedrum" },
		{ AL["Ok'thor the Breaker"], "BRDOkthor" },
		{ AL["Theldren"], "BRDTheldren" },
		{ AL["Houndmaster Grebmar"], "BRDHoundmaster" },
		{ AL["Pyromancer Loregrain"].." ("..AL["Rare"]..")", "BRDPyromancerLoregrain" },
		{ AL["The Vault"], "BRDTheVault" },
		{ AL["Warder Stilgiss"].." ("..AL["Rare"]..")", "BRDWarderStilgiss" },
		{ AL["Verek"].." ("..AL["Rare"]..")", "BRDVerek" },
		{ AL["Fineous Darkvire"], "BRDFineousDarkvire" },
		{ AL["Lord Incendius"], "BRDLordIncendius" },
		{ AL["Bael'Gar"], "BRDBaelGar" },
		{ AL["General Angerforge"], "BRDGeneralAngerforge" },
		{ AL["Golem Lord Argelmach"], "BRDGolemLordArgelmach" },
		{ AL["The Grim Guzzler"], "BRDGuzzler" },
		{ AL["Ambassador Flamelash"], "BRDFlamelash" },
		{ AL["Panzor the Invincible"].." ("..AL["Rare"]..")", "BRDPanzor" },
		{ AL["Summoner's Tomb"], "BRDTomb" },
		{ AL["Magmus"], "BRDMagmus" },
		{ AL["Princess Moira Bronzebeard"], "BRDPrincess" },
		{ AL["Emperor Dagran Thaurissan"], "BRDEmperorDagranThaurissan" },
		{ AL["Trash Mobs"], "BRDTrash" },
	},
	["LowerBlackrock"] = {
		{ AL["Spirestone Butcher"].." ("..AL["Rare"]..")", "LBRSSpirestoneButcher" },
		{ AL["Spirestone Battle Lord"].." ("..AL["Rare"]..")", "LBRSSpirestoneBattleLord" },
		{ AL["Spirestone Lord Magus"].." ("..AL["Rare"]..")", "LBRSSpirestoneLordMagus" },
		{ AL["Highlord Omokk"], "LBRSOmokk" },
		{ AL["Shadow Hunter Vosh'gajin"], "LBRSVosh" },
		{ AL["War Master Voone"], "LBRSVoone" },
		{ AL["Burning Felguard"].." ("..AL["Rare"]..")", "LBRSFelguard" },
		{ AL["Mor Grayhoof"], "LBRSGrayhoof" },
		{ AL["Bannok Grimaxe"].." ("..AL["Rare"]..")", "LBRSGrimaxe" },
		{ AL["Mother Smolderweb"], "LBRSSmolderweb" },
		{ AL["Crystal Fang"].." ("..AL["Rare"]..")", "LBRSCrystalFang" },
		{ AL["Urok Doomhowl"], "LBRSDoomhowl" },
		{ AL["Quartermaster Zigris"], "LBRSZigris" },
		{ AL["Halycon"], "LBRSHalycon" },
		{ AL["Gizrul the Slavener"], "LBRSSlavener" },
		{ AL["Ghok Bashguud"].." ("..AL["Rare"]..")", "LBRSBashguud" },
		{ AL["Overlord Wyrmthalak"], "LBRSWyrmthalak" },
		{ AL["Trash Mobs"], "LBRSTrash" },
	},
	["UpperBlackrock"] = {
		{ AL["Pyroguard Emberseer"], "UBRSEmberseer" },
		{ AL["Solakar Flamewreath"], "UBRSSolakar" },
		{ AL["Father Flame"], "UBRSFlame" },
		{ AL["Jed Runewatcher"].." ("..AL["Rare"]..")", "UBRSRunewatcher" },
		{ AL["Goraluk Anvilcrack"].." ("..AL["Rare"]..")", "UBRSAnvilcrack" },
		{ AL["Warchief Rend Blackhand"], "UBRSRend" },
		{ AL["Gyth"], "UBRSGyth" },
		{ AL["The Beast"], "UBRSBeast" },
		{ AL["Lord Valthalak"], "UBRSValthalak" },
		{ AL["General Drakkisath"], "UBRSDrakkisath" },
		{ AL["Trash Mobs"], "UBRSTrash" },
	},
	["KarazhanCrypt"] = {
		{ AL["Marrowspike"], "KCMarrowspike" },
		{ AL["Hivaxxis"], "KCHivaxxis" },
		{ AL["Corpsemuncher"], "KCCorpsemuncher" },
		{ AL["Guard Captain Gort"], "KCGuardCaptainGort" },
		{ AL["Archlich Enkhraz"], "KCArchlichEnkhraz" },
		{ AL["Commander Andreon"], "KCCommanderAndreon" },
		{ AL["Alarus"], "KCAlarus" },
		{ AL["Half-Buried Treasure Chest"], "KCTreasure" },
		{ AL["Trash Mobs"], "KCTrash" },
	},
	["CavernsOfTimeBlackMorass"] = {
		{ AL["Chronar"], "COTBMChronar" },
		{ AL["Epidamu"], "COTBMEpidamu" },
		{ AL["Drifting Avatar of Sand"], "COTBMDriftingAvatar" },
		{ AL["Time-Lord Epochronos"], "COTBMTimeLordEpochronos" },
		{ AL["Mossheart"], "COTBMMossheart" },
		{ AL["Rotmaw"], "COTBMRotmaw" },
		{ AL["Antnormi"], "COTBMAntnormi" },
		{ AL["Trash Mobs"], "COTTrash" },
		-- { AL["Infinite Chromie"], "COTBMInfiniteChromie" },
	},
	["StormwindVault"] = {
		{ AL["Aszosh Grimflame"], "SWVAszoshGrimflame" },
		{ AL["Tham'Grarr"], "SWVThamGrarr" },
		{ AL["Black Bride"], "SWVBlackBride" },
		{ AL["Damian"], "SWVDamian" },
		{ AL["Volkan Cruelblade"], "SWVVolkanCruelblade" },
		{ AL["Arc'tiras"], "SWVVaultArmoryEquipment" },
		{ AL["Trash Mobs"], "SWVTrash" },
	},
	["BlackwingLair"] = {
		{ AL["Razorgore the Untamed"], "BWLRazorgore" },
		{ AL["Vaelastrasz the Corrupt"], "BWLVaelastrasz" },
		{ AL["Broodlord Lashlayer"], "BWLLashlayer" },
		{ AL["Firemaw"], "BWLFiremaw" },
		{ AL["Ezzel Darkbrewer"], "BWLEzzel" },
		{ AL["Ebonroc"], "BWLEbonroc" },
		{ AL["Flamegor"], "BWLFlamegor" },
		{ AL["Chromaggus"], "BWLChromaggus" },
		{ AL["Nefarian"], "BWLNefarian" },
		{ AL["Trash Mobs"], "BWLTrashMobs" },
	},
	["Deadmines"] = {
		{ AL["Jared Voss"], "DMJaredVoss" },
		{ AL["Rhahk'Zor"], "DMRhahkZor" },
		{ AL["Miner Johnson"].." ("..AL["Rare"]..")", "DMMinerJohnson" },
		{ AL["Sneed"], "DMSneed" },
		{ AL["Sneed's Shredder"], "DMSneedsShredder" },
		{ AL["Gilnid"], "DMGilnid" },
		{ AL["Masterpiece Harvester"], "DMHarvester" },
		{ AL["Mr. Smite"], "DMMrSmite" },
		{ AL["Cookie"], "DMCookie" },
		{ AL["Captain Greenskin"], "DMCaptainGreenskin" },
		{ AL["Edwin VanCleef"], "DMVanCleef" },
		{ AL["Trash Mobs"], "DMTrash" },
	},
	["TheCrescentGrove"] = {
		{ AL["Grovetender Engryss"], "TCGGrovetenderEngryss" },
		{ AL["Keeper Ranathos"], "TCGKeeperRanathos" },
		{ AL["High Priestess A'lathea"], "TCGHighPriestessAlathea" },
		{ AL["Fenektis the Deceiver"], "TCGFenektistheDeceiver" },
		{ AL["Master Raxxieth"], "TCGMasterRaxxieth" },
		{ AL["Trash Mobs"], "TCGTrash" },
	},
	["Gnomeregan"] = {
		{ AL["Grubbis"], "GnGrubbis" },
		{ AL["Viscous Fallout"], "GnViscousFallout" },
		{ AL["Electrocutioner 6000"], "GnElectrocutioner6000" },
		{ AL["Crowd Pummeler 9-60"], "GnCrowdPummeler960" },
		{ AL["Dark Iron Ambassador"], "GnDIAmbassador" },
		{ AL["Mekgineer Thermaplugg"], "GnMekgineerThermaplugg" },
		{ AL["Trash Mobs"], "GnTrash" },
	},
	["MoltenCore"] = {
		{ AL["Incindis"], "MCIncindis" },
		{ AL["Lucifron"], "MCLucifron" },
		{ AL["Magmadar"], "MCMagmadar" },
		-- { AL["Gehennas"], "MCGehennas" },
		{ AL["Garr"], "MCGarr" },
		{ AL["Shazzrah"], "MCShazzrah" },
		{ AL["Baron Geddon"], "MCGeddon" },
		{ AL["Golemagg the Incinerator"], "MCGolemagg" },
		{ AL["Basalthar & Smoldaris"], "MCTwins" },
		{ AL["Sorcerer-Thane Thaurissan"], "MCThaurissan" },
		{ AL["Sulfuron Harbinger"], "MCSulfuron" },
		{ AL["Majordomo Executus"], "MCMajordomo" },
		{ AL["Ragnaros"], "MCRagnaros" },
		{ AL["Trash Mobs"], "MCTrashMobs" },
		{ AL["Random Boss Loot"], "MCRANDOMBOSSDROPS" },
	},
	["Naxxramas"] = {
		{ AL["Patchwerk"], "NAXPatchwerk" },
		{ AL["Grobbulus"], "NAXGrobbulus" },
		{ AL["Gluth"], "NAXGluth" },
		{ AL["Thaddius"], "NAXThaddius" },
		{ AL["Anub'Rekhan"], "NAXAnubRekhan" },
		{ AL["Grand Widow Faerlina"], "NAXGrandWidowFaerlina" },
		{ AL["Maexxna"], "NAXMaexxna" },
		{ AL["Noth the Plaguebringer"], "NAXNoththePlaguebringer" },
		{ AL["Heigan the Unclean"], "NAXHeigantheUnclean" },
		{ AL["Loatheb"], "NAXLoatheb" },
		{ AL["Instructor Razuvious"], "NAXInstructorRazuvious" },
		{ AL["Gothik the Harvester"], "NAXGothiktheHarvester" },
		{ AL["The Four Horsemen"], "NAXTheFourHorsemen" },
		{ AL["Sapphiron"], "NAXSapphiron" },
		{ AL["Kel'Thuzad"], "NAXKelThuzard" },
		{ AL["Trash Mobs"], "NAXTrash" },
	},
	["SMGraveyard"] = {
		{ AL["Interrogator Vishas"], "SMVishas" },
		{ AL["Duke Dreadmoore"], "SMDukeDreadmoore" },
		{ AL["Scorn"].." ("..AL["Scourge Invasion"]..")", "SMScorn" },
		{ AL["Ironspine"].." ("..AL["Rare"]..")", "SMIronspine" },
		{ AL["Azshir the Sleepless"].." ("..AL["Rare"]..")", "SMAzshir" },
		{ AL["Fallen Champion"].." ("..AL["Rare"]..")", "SMFallenChampion" },
		{ AL["Bloodmage Thalnos"], "SMBloodmageThalnos" },
		{ AL["Trash Mobs"], "SMGTrash" },
	},
	["SMLibrary"] = {
		{ AL["Houndmaster Loksey"], "SMHoundmasterLoksey" },
		{ AL["Brother Wystan"], "SMBrotherWystan" },
		{ AL["Arcanist Doan"], "SMDoan" },
		{ AL["Trash Mobs"], "SMLTrash" },
	},
	["SMArmory"] = {
		{ AL["Herod"], "SMHerod" },
		{ AL["Armory Quartermaster Daghelm"], "SMQuartermaster" },
		{ AL["Trash Mobs"], "SMATrash" },
	},
	["SMCathedral"] = {
		{ AL["High Inquisitor Fairbanks"], "SMFairbanks" },
		{ AL["Scarlet Commander Mograine"], "SMMograine" },
		{ AL["High Inquisitor Whitemane"], "SMWhitemane" },
		{ AL["Trash Mobs"], "SMCTrash" },
	},
	["Scholomance"] = {
		-- { AL["Blood Steward of Kirtonos"], "SCHOLOBlood" },
		{ AL["Kirtonos the Herald"], "SCHOLOKirtonostheHerald" },
		{ AL["Jandice Barov"], "SCHOLOJandiceBarov" },
		{ AL["Lord Blackwood"].." ("..AL["Scourge Invasion"]..")", "SCHOLOLordBlackwood" },
		{ AL["Rattlegore"], "SCHOLORattlegore" },
		{ AL["Death Knight Darkreaver"], "SCHOLODeathKnight" },
		{ AL["Marduk Blackpool"], "SCHOLOMarduk" },
		{ AL["Vectus"], "SCHOLOVectus" },
		{ AL["Ras Frostwhisper"], "SCHOLORasFrostwhisper" },
		{ AL["Kormok"], "SCHOLOKormok" },
		{ AL["Instructor Malicia"], "SCHOLOInstructorMalicia" },
		{ AL["Doctor Theolen Krastinov"], "SCHOLODoctorTheolenKrastinov" },
		{ AL["Lorekeeper Polkelt"], "SCHOLOLorekeeperPolkelt" },
		{ AL["The Ravenian"], "SCHOLOTheRavenian" },
		{ AL["Lord Alexei Barov"], "SCHOLOLordAlexeiBarov" },
		{ AL["Lady Illucia Barov"], "SCHOLOLadyIlluciaBarov" },
		{ AL["Darkmaster Gandling"], "SCHOLODarkmasterGandling" },
		{ AL["Trash Mobs"], "SCHOLOTrash" },
	},
	["ShadowfangKeep"] = {
		{ AL["Rethilgore"], "SFKRethilgore" },
		{ AL["Fel Steed"], "SFKFelSteed" },
		{ AL["Razorclaw the Butcher"], "SFKRazorclawtheButcher" },
		{ AL["Baron Silverlaine"], "SFKSilverlaine" },
		{ AL["Commander Springvale"], "SFKSpringvale" },
		{ AL["Sever"].." ("..AL["Scourge Invasion"]..")", "SFKSever" },
		{ AL["Odo the Blindwatcher"], "SFKOdotheBlindwatcher" },
		{ AL["Deathsworn Captain"].." ("..AL["Rare"]..")", "SFKDeathswornCaptain" },
		{ AL["Fenrus the Devourer"], "SFKFenrustheDevourer" },
		{ AL["Arugal's Voidwalker"], "SFKArugalsVoidwalker" },
		{ AL["Wolf Master Nandos"], "SFKWolfMasterNandos" },
		{ AL["Archmage Arugal"], "SFKArchmageArugal" },
		{ AL["Prelate Ironmane"], "SFKPrelate" },
		{ AL["Trash Mobs"], "SFKTrash" },
	},
	["TheStockade"] = {
		{ AL["Targorr the Dread"], "SWStTargorr" },
		{ AL["Kam Deepfury"], "SWStKamDeepfury" },
		{ AL["Hamhock"], "SWStHamhock" },
		{ AL["Dextren Ward"], "SWStDextren" },
		{ AL["Bazil Thredd"], "SWStBazil" },
		{ AL["Bruegal Ironknuckle"].." ("..AL["Rare"]..")", "SWStBruegalIronknuckle" },
		{ AL["Trash Mobs"], "SWStTrash" },
	},
	["Stratholme"] = {
		{ AL["Skul"].." ("..AL["Rare"]..")", "STRATSkull" },
		{ AL["Stratholme Courier"], "STRATStratholmeCourier" },
		{ AL["Postmaster Malown"], "STRATPostmaster" },
		{ AL["Fras Siabi"], "STRATFrasSiabi" },
		{ AL["Atiesh"], "STRATAtiesh" },
		{ AL["Balzaphon"].." ("..AL["Scourge Invasion"]..")", "STRATBalzaphon" },
		{ AL["Hearthsinger Forresten"].." ("..AL["Rare"]..")", "STRATHearthsingerForresten" },
		{ AL["The Unforgiven"], "STRATTheUnforgiven" },
		{ AL["Timmy the Cruel"], "STRATTimmytheCruel" },
		{ AL["Malor the Zealous"], "STRATMalor" },
		{ AL["Malor's Strongbox"], "STRATMalorsStrongbox" },
		{ AL["Crimson Hammersmith"], "STRATCrimsonHammersmith" },
		{ AL["Cannon Master Willey"], "STRATCannonMasterWilley" },
		{ AL["Archivist Galford"], "STRATArchivistGalford" },
		{ AL["Balnazzar"], "STRATBalnazzar" },
		{ AL["Sothos"].." & "..AL["Jarien"], "STRATSothosJarien" },
		{ AL["Stonespine"].." ("..AL["Rare"]..")", "STRATStonespine" },
		{ AL["Baroness Anastari"], "STRATBaronessAnastari" },
		{ AL["Black Guard Swordsmith"], "STRATBlackGuardSwordsmith" },
		{ AL["Nerub'enkan"], "STRATNerubenkan" },
		{ AL["Maleki the Pallid"], "STRATMalekithePallid" },
		{ AL["Magistrate Barthilas"], "STRATMagistrateBarthilas" },
		{ AL["Ramstein the Gorger"], "STRATRamsteintheGorger" },
		{ AL["Baron Rivendare"], "STRATBaronRivendare" },
		{ AL["Trash Mobs"], "STRATTrash" },
	},
	["SunkenTemple"] = {
		{ AL["Balcony Minibosses"], "STBalconyMinibosses" },
		{ AL["Atal'alarion"], "STAtalalarion" },
		{ AL["Spawn of Hakkar"], "STSpawnOfHakkar" },
		{ AL["Avatar of Hakkar"], "STAvatarofHakkar" },
		{ AL["Jammal'an the Prophet"], "STJammalan" },
		{ AL["Ogom the Wretched"], "STOgom" },
		{ AL["Dreamscythe"], "STDreamscythe" },
		{ AL["Weaver"], "STWeaver" },
		{ AL["Morphaz"], "STMorphaz" },
		{ AL["Hazzas"], "STHazzas" },
		{ AL["Shade of Eranikus"], "STEranikus" },
		{ AL["Trash Mobs"], "STTrash" },
	},
	["Uldaman"] = {
		{ AL["Baelog"], "UldBaelog" },
		{ AL["Olaf"], "UldOlaf" },
		{ AL["Eric 'The Swift'"], "UldEric" },
		{ AL["Revelosh"], "UldRevelosh" },
		{ AL["Ironaya"], "UldIronaya" },
		{ AL["Ancient Stone Keeper"], "UldAncientStoneKeeper" },
		{ AL["Galgann Firehammer"], "UldGalgannFirehammer" },
		{ AL["Grimlok"], "UldGrimlok" },
		{ AL["Archaedas"], "UldArchaedas" },
		{ AL["Trash Mobs"], "UldTrash" },
	},
	["GilneasCity"] = {
		{ AL["Matthias Holtz"], "GCMatthiasHoltz" },
		{ AL["Packmaster Ragetooth"], "GCPackmasterRagetooth" },
		{ AL["Judge Sutherland"], "GCJudgeSutherland" },
		{ AL["Dustivan Blackcowl"], "GCDustivanBlackcowl" },
		{ AL["Marshal Magnus Greystone"], "GCMarshalMagnusGreystone" },
		{ AL["Horsemaster Levvin"], "GCHorsemasterLevvin" },
		{ AL["Harlow Family Chest"], "GCHarlowFamilyChest" },
		{ AL["Genn Greymane"], "GCGennGreymane" },
		{ AL["Trash Mobs"], "GCTrash" },
	},
	["ZulGurub"] = {
		{ AL["High Priestess Jeklik"], "ZGJeklik" },
		{ AL["High Priest Venoxis"], "ZGVenoxis" },
		{ AL["High Priestess Mar'li"], "ZGMarli" },
		{ AL["Bloodlord Mandokir"], "ZGMandokir" },
		{ AL["Gri'lek"], "ZGGrilek" },
		{ AL["Hazza'rah"], "ZGHazzarah" },
		{ AL["Renataki"], "ZGRenataki" },
		{ AL["Wushoolay"], "ZGWushoolay" },
		{ AL["Gahz'ranka"], "ZGGahzranka" },
		{ AL["High Priest Thekal"], "ZGThekal" },
		{ AL["High Priestess Arlokk"], "ZGArlokk" },
		{ AL["Jin'do the Hexxer"], "ZGJindo" },
		{ AL["Hakkar"], "ZGHakkar" },
		{ AL["Random Boss Loot"], "ZGShared" },
		{ AL["Trash Mobs"], "ZGTrash1" },
		{ AL["ZG Enchants"], "ZGEnchants" },
	},
	["BlackfathomDeeps"] = {
		{ AL["Ghamoo-ra"], "BFDGhamoora" },
		{ AL["Lady Sarevess"], "BFDLadySarevess" },
		{ AL["Gelihast"], "BFDGelihast" },
		{ AL["Baron Aquanis"], "BFDBaronAquanis" },
		{ AL["Velthelaxx the Defiler"], "BFDVelthelaxx" },
		{ AL["Twilight Lord Kelris"], "BFDTwilightLordKelris" },
		{ AL["Old Serra'kis"], "BFDOldSerrakis" },
		{ AL["Aku'mai"], "BFDAkumai" },
		{ AL["Trash Mobs"], "BFDTrash" },
	},
	["DireMaulEast"] = {
		{ AL["Pusillin"], "DMEPusillin" },
		{ AL["Zevrim Thornhoof"], "DMEZevrimThornhoof" },
		{ AL["Hydrospawn"], "DMEHydro" },
		{ AL["Lethtendris"], "DMELethtendris" },
		{ AL["Pimgib"], "DMEPimgib" },
		{ AL["Isalien"], "DMEIsalien" },
		{ AL["Alzzin the Wildshaper"], "DMEAlzzin" },
		{ AL["Trash Mobs"], "DMETrash" },
		{ AL["Dire Maul Books"], "DMEBooks" },
	},
	["DireMaulWest"] = {
		{ AL["Tendris Warpwood"], "DMWTendrisWarpwood" },
		{ AL["Illyanna Ravenoak"], "DMWIllyannaRavenoak" },
		{ AL["Magister Kalendris"], "DMWMagisterKalendris" },
		{ AL["Tsu'zee"].." ("..AL["Rare"]..")", "DMWTsuzee" },
		{ AL["Revanchion"].." ("..AL["Scourge Invasion"]..")", "DMWRevanchion" },
		{ AL["Immol'thar"], "DMWImmolthar" },
		{ AL["Lord Hel'nurath"].." ("..AL["Rare"]..")", "DMWHelnurath" },
		{ AL["Prince Tortheldrin"], "DMWPrinceTortheldrin" },
		{ AL["Trash Mobs"], "DMWTrash" },
		{ AL["Dire Maul Books"], "DMWBooks" },
	},
	["DireMaulNorth"] = {
		{ AL["Guard Mol'dar"], "DMNGuardMoldar" },
		{ AL["Stomper Kreeg"], "DMNStomperKreeg" },
		{ AL["Guard Fengus"], "DMNGuardFengus" },
		{ AL["Knot Thimblejack"], "DMNThimblejack" },
		{ AL["Guard Slip'kik"], "DMNGuardSlipkik" },
		{ AL["Captain Kromcrush"], "DMNCaptainKromcrush" },
		{ AL["Cho'Rush the Observer"], "DMNChoRush" },
		{ AL["King Gordok"], "DMNKingGordok" },
		{ AL["Tribute Run"], "DMNTRIBUTERUN" },
		{ AL["Trash Mobs"], "DMNTrash" },
		{ AL["Dire Maul Books"], "DMNBooks" },
	},
	["Maraudon"] = {
		{ AL["Noxxion"], "MaraNoxxion" },
		{ AL["Razorlash"], "MaraRazorlash" },
		{ AL["Lord Vyletongue"], "MaraLordVyletongue" },
		{ AL["Meshlok the Harvester"].." ("..AL["Rare"]..")", "MaraMeshlok" },
		{ AL["Celebras the Cursed"], "MaraCelebras" },
		{ AL["Landslide"], "MaraLandslide" },
		{ AL["Tinkerer Gizlock"], "MaraTinkererGizlock" },
		{ AL["Rotgrip"], "MaraRotgrip" },
		{ AL["Princess Theradras"], "MaraPrincessTheradras" },
		{ AL["Trash Mobs"], "MaraTrash" },
	},
	["Onyxia"] = {
		{ AL["Broodcommander Axelus"], "Axelus" },
		{ AL["Onyxia"], "Onyxia" },
	},
	["RagefireChasm"] = {
		{ AL["Taragaman the Hungerer"], "RFCTaragaman" },
		{ AL["Oggleflint"], "RFCOggleflint" },
		{ AL["Jergosh the Invoker"], "RFCJergosh" },
		{ AL["Bazzalan"], "RFCBazzalan" },
	},
	["RazorfenDowns"] = {
		{ AL["Tuten'kash"], "RFDTutenkash" },
		{ AL["Lady Falther'ess"].." ("..AL["Scourge Invasion"]..")", "RFDLadyF" },
		{ AL["Plaguemaw the Rotting"], "RFDPlaguemaw" },
		{ AL["Mordresh Fire Eye"], "RFDMordreshFireEye" },
		{ AL["Glutton"], "RFDGlutton" },
		{ AL["Death Prophet Rakameg"], "RFDDeathProphet" },
		{ AL["Ragglesnout"].." ("..AL["Rare"]..")", "RFDRagglesnout" },
		{ AL["Amnennar the Coldbringer"], "RFDAmnennar" },
		{ AL["Trash Mobs"], "RFDTrash" },
	},
	["RazorfenKraul"] = {
		{ AL["Aggem Thorncurse"], "RFKAggem" },
		{ AL["Death Speaker Jargba"], "RFKDeathSpeakerJargba" },
		{ AL["Overlord Ramtusk"], "RFKOverlordRamtusk" },
		{ AL["Razorfen Spearhide"].." ("..AL["Rare"]..")", "RFKRazorfenSpearhide" },
		{ AL["Agathelos the Raging"], "RFKAgathelos" },
		{ AL["Blind Hunter"].." ("..AL["Rare"]..")", "RFKBlindHunter" },
		{ AL["Charlga Razorflank"], "RFKCharlgaRazorflank" },
		{ AL["Earthcaller Halmgar"].." ("..AL["Rare"]..")", "RFKEarthcallerHalmgar" },
		{ AL["Rotthorn"], "RFKRotthorn" },
		{ AL["Trash Mobs"], "RFKTrash" },
	},
	["RuinsofAQ"] = {
		{ AL["Kurinnaxx"], "AQ20Kurinnaxx" },
		{ AL["Lieutenant General Andorov"], "AQ20Andorov" },
		{ AL["Rajaxx's Captains"], "AQ20CAPTAIN" },
		{ AL["General Rajaxx"], "AQ20Rajaxx" },
		{ AL["Moam"], "AQ20Moam" },
		{ AL["Buru the Gorger"], "AQ20Buru" },
		{ AL["Ayamiss the Hunter"], "AQ20Ayamiss" },
		{ AL["Ossirian the Unscarred"], "AQ20Ossirian" },
		{ AL["Trash Mobs"], "AQ20Trash" },
		{ AL[ "Class Books"],nil, "AQ20ClassBooks" },
		{ AL["AQ Enchants"], "AQ20Enchants" },
	},
	["TempleofAQ"] = {
		{ AL["The Prophet Skeram"], "AQ40Skeram" },
		{ AL["The Bug Family"], "AQ40Trio" },
		{ AL["Battleguard Sartura"], "AQ40Sartura" },
		{ AL["Fankriss the Unyielding"], "AQ40Fankriss" },
		{ AL["Viscidus"], "AQ40Viscidus" },
		{ AL["Princess Huhuran"], "AQ40Huhuran" },
		{ AL["The Twin Emperors"], "AQ40Emperors" },
		{ AL["Ouro"], "AQ40Ouro" },
		{ AL["C'Thun"], "AQ40CThun" },
		{ AL["Trash Mobs"], "AQ40Trash1" },
		{ AL["Trash Mobs"], "AQ40Trash2" },
		{ AL["AQ Enchants"], "AQEnchants" },
		{ AL["AQ Opening Quest Chain"], "AQOpening" },
	},
	["WailingCaverns"] = {
		{ AL["Lord Cobrahn"], "WCLordCobrahn" },
		{ AL["Lady Anacondra"], "WCLadyAnacondra" },
		{ AL["Kresh"], "WCKresh" },
		{ AL["Deviate Faerie Dragon"].." ("..AL["Rare"]..")", "WCDeviateFaerieDragon" },
		{ AL["Zandara Windhoof"], "WCZandara" },
		{ AL["Lord Pythas"], "WCLordPythas" },
		{ AL["Skum"], "WCSkum" },
		{ AL["Vangros"], "WCVangros" },
		{ AL["Lord Serpentis"], "WCLordSerpentis" },
		{ AL["Verdan the Everliving"], "WCVerdan" },
		{ AL["Mutanus the Devourer"], "WCMutanus" },
		{ AL["Trash Mobs"], "WCTrash" },
	},
	["ZulFarrak"] = {
		{ AL["Antu'sul"], "ZFAntusul" },
		{ AL["Witch Doctor Zum'rah"], "ZFWitchDoctorZumrah" },
		{ AL["Shadowpriest Sezz'ziz"], "ZFSezzziz" },
		{ AL["Dustwraith"].." ("..AL["Rare"]..")", "ZFDustwraith" },
		{ AL["Zerillis"].." ("..AL["Rare"]..")", "ZFZerillis" },
		{ AL["Gahz'rilla"], "ZFGahzrilla" },
		{ AL["Chief Ukorz Sandscalp"], "ZFChiefUkorzSandscalp" },
		{ AL["Zel'jeb the Ancient"], "ZFZeljeb" },
		{ AL["Champion Razjal the Quick"], "ZFChampion" },
		{ AL["Trash Mobs"], "ZFTrash" },
	},
	["EmeraldSanctum"] = {
		{ AL["Erennius"], "ESErennius" },
		{ AL["Solnius the Awakener"], "ESSolnius1" },
		{ AL["Favor of Erennius (ES Hard Mode)"], "ESHardMode" },
		{ AL["Trash Mobs"], "ESTrash" },
	},
	["LowerKara"] = {
		{ AL["Master Blacksmith Rolfen"], "LKHRolfen" },
		{ AL["Brood Queen Araxxna"], "LKHBroodQueenAraxxna" },
		{ AL["Grizikil"], "LKHGrizikil" },
		{ AL["Clawlord Howlfang"], "LKHClawlordHowlfang" },
		{ AL["Lord Blackwald II"], "LKHLordBlackwaldII" },
		{ AL["Moroes"], "LKHMoroes" },
		{ AL["Trash Mobs"], "LKHTrash" },
		{ AL["LKH Enchants"], "LKHEnchants" },
	},
	["UpperKara"] = {
		{ AL["Keeper Gnarlmoon"], "UKHGnarlmoon" },
		{ AL["Ley-Watcher Incantagos"], "UKHIncantagos" },
		{ AL["Anomalus"], "UKHAnomalus" },
		{ AL["Echo of Medivh"], "UKHEcho" },
		{ AL["King (Chess fight)"], "UKHKing" },
		{ AL["Sanv Tas'dal"], "UKHSanvTasdal" },
		{ AL["Kruul"], "UKHKruul" },
		{ AL["Rupturan the Broken"], "UKHRupturan" },
		{ AL["Mephistroth"], "UKHMephistroth" },
		{ AL["Trash Mobs"], "UKHTrash" },
	},
	["WorldBosses"] = {
		{ AL["Azuregos"], "AAzuregos" },
		{ AL["Emeriss"], "DEmeriss" },
		{ AL["Lethon"], "DLethon" },
		{ AL["Taerar"], "DTaerar" },
		{ AL["Ysondre"], "DYsondre" },
		{ AL["Lord Kazzak"], "KKazzak" },
		{ AL["Nerubian Overseer"], "Nerubian" },
		{ AL["Dark Reaver of Karazhan"], "Reaver" },
		{ AL["Ostarius"], "Ostarius" },
		{ AL["Concavius"], "Concavius" },
		{ AL["Moo"], "CowKing" },
		{ AL["Cla'ckora"], "Clackora" },
	},
	["RareSpawns"] = {
		{ WHITE.."[17]"..DEFAULT.." "..AL["Earthcaller Rezengal"].." "..WHITE.."("..AL["Stonetalon Mountains"]..")", "EarthcallerRezengal" },
		{ WHITE.."[17]"..DEFAULT.." "..AL["Shade Mage"].." "..WHITE.."("..AL["Tirisfal Glades"]..")", "ShadeMage" },
		{ WHITE.."[18]"..DEFAULT.." "..AL["Graypaw Alpha"].." "..WHITE.."("..AL["Tirisfal Glades"]..")", "GraypawAlpha" },
		{ WHITE.."[24]"..DEFAULT.." "..AL["Blazespark"].." "..WHITE.."("..AL["Stonetalon Mountains"]..")", "Blazespark" },
		{ WHITE.."[35]"..DEFAULT.." "..AL["Witch Doctor Tan'zo"].." "..WHITE.."("..AL["Arathi Highlands"]..")", "WitchDoctorTanzo" },
		{ WHITE.."[40]"..DEFAULT.." "..AL["Widow of the Woods"].." "..WHITE.."("..AL["Gilneas"]..")", "WidowoftheWoods" },
		{ WHITE.."[40]"..DEFAULT.." "..AL["Dawnhowl"].." "..WHITE.."("..AL["Gilneas"]..")", "Dawnhowl" },
		{ WHITE.."[43]"..DEFAULT.." "..AL["Maltimor's Prototype"].." "..WHITE.."("..AL["Gilneas"]..")", "MaltimorsPrototype" },
		{ WHITE.."[44]"..DEFAULT.." "..AL["Bonecruncher"].." "..WHITE.."("..AL["Gilneas"]..")", "Bonecruncher" },
		{ WHITE.."[44]"..DEFAULT.." "..AL["Duskskitter"].." "..WHITE.."("..AL["Gilneas"]..")", "Duskskitter" },
		{ WHITE.."[45]"..DEFAULT.." "..AL["Baron Perenolde"].." "..WHITE.."("..AL["Gilneas"]..")", "BaronPerenolde" },
		{ WHITE.."[45]"..DEFAULT.." "..AL["Kin'Tozo"].." "..WHITE.."("..AL["Stranglethorn Vale"]..")", "KinTozo" },
		{ WHITE.."[47]"..DEFAULT.." "..AL["Grug'thok the Seer"].." "..WHITE.."("..AL["Feralas"]..")", "Grugthok" },
		{ WHITE.."[47]"..DEFAULT.." "..AL["M-0L1Y"].." "..WHITE.."("..AL["Dun Morogh"]..")", "M0L1Y" },
		{ WHITE.."[49]"..DEFAULT.." "..AL["Explorer Ashbeard"].." "..WHITE.."("..AL["Searing Gorge"]..")", "Ashbeard" },
		{ WHITE.."[50]"..DEFAULT.." "..AL["Jal'akar"].." "..WHITE.."("..AL["Hinterlands"]..")", "Jalakar" },
		{ WHITE.."[51]"..DEFAULT.." "..AL["Embereye"].." "..WHITE.."("..AL["Gilijim Isle"]..")", "Embereye" },
		{ WHITE.."[51]"..DEFAULT.." "..AL["Ruk'thok the Pyromancer"].." "..WHITE.."("..AL["Lapidis Isle"]..")", "Rukthok" },
		{ WHITE.."[51]"..DEFAULT.." "..AL["Tarangos"].." "..WHITE.."("..AL["Azshara"]..")", "Tarangos" },
		{ WHITE.."[51]"..DEFAULT.." "..AL["Ripjaw"].." "..WHITE.."("..AL["Lapidis Isle"]..")", "Ripjaw" },
		{ WHITE.."[53]"..DEFAULT.." "..AL["Xalvic Blackclaw"].." "..WHITE.."("..AL["Felwood"]..")", "Xalvic" },
		{ WHITE.."[54]"..DEFAULT.." "..AL["Aquitus"].." "..WHITE.."("..AL["Gilijim Isle"]..")", "Aquitus" },
		{ WHITE.."[55]"..DEFAULT.." "..AL["Firstborn of Arugal"].." "..WHITE.."("..AL["Gilneas"]..")", "FirstbornofArugal" },
		{ WHITE.."[55]"..DEFAULT.." "..AL["Letashaz"].." "..WHITE.."("..AL["Gilijim Isle"]..")", "Letashaz" },
		{ WHITE.."[55]"..DEFAULT.." "..AL["Margon the Mighty"].." "..WHITE.."("..AL["Lapidis Isle"]..")", "MargontheMighty" },
		{ WHITE.."[55]"..DEFAULT.." "..AL["The Wandering Knight"].." "..WHITE.."("..AL["Western Plaguelands"]..")", "WanderingKnight" },
		{ WHITE.."[56]"..DEFAULT.." "..AL["Stoneshell"].." "..WHITE.."("..AL["Tel'abim"]..")", "Stoneshell" },
		{ WHITE.."[57]"..DEFAULT.." "..AL["Zareth Terrorblade"].." "..WHITE.."("..AL["Blasted Lands"]..")", "Zareth" },
		{ WHITE.."[58]"..DEFAULT.." "..AL["Highvale Silverback"].." "..WHITE.."("..AL["Tel'abim"]..")", "HighvaleSilverback" },
		{ WHITE.."[58]"..DEFAULT.." "..AL["Mallon The Moontouched"].." "..WHITE.."("..AL["Winterspring"]..")", "Mallon" },
		{ WHITE.."[59]"..DEFAULT.." "..AL["Blademaster Kargron"].." "..WHITE.."("..AL["Burning Steppes"]..")", "Kargron" },
		{ WHITE.."[59]"..DEFAULT.." "..AL["Professor Lysander"].." "..WHITE.."("..AL["Eastern Plaguelands"]..")", "ProfessorLysander" },
		{ WHITE.."[60]"..DEFAULT.." "..AL["Admiral Barean Westwind"].." "..WHITE.."("..AL["Scarlet Enclave"]..")", "AdmiralBareanWestwind" },
		{ WHITE.."[60]"..DEFAULT.." "..AL["Azurebeak"].." "..WHITE.."("..AL["Hyjal"]..")", "Azurebeak" },
		{ WHITE.."[60]"..DEFAULT.." "..AL["Barkskin Fisher"].." "..WHITE.."("..AL["Hyjal"]..")", "BarkskinFisher" },
		{ WHITE.."[61]"..DEFAULT.." "..AL["Crusader Larsarius"].." "..WHITE.."("..AL["Eastern Plaguelands"]..")", "CrusaderLarsarius" },
		{ WHITE.."[61]"..DEFAULT.." "..AL["Shadeflayer Goliath"].." "..WHITE.."("..AL["Hyjal"]..")", "ShadeflayerGoliath" },
	},
	["DragonmawRetreat"] = {
		{ AL["Gowlfang"], "DMRGowlfang" },
		{ AL["Cavernweb Broodmother"], "DMRBroodmother" },
		{ AL["Web Master Torkon"], "DMRWebMaster" },
		{ AL["Garlok Flamekeeper"], "DMRGarlok" },
		{ AL["Halgan Redbrand"], "DMRHalgan" },
		{ AL["Slagfist Destroyer"], "DMRSlagfist" },
		{ AL["Overlord Blackheart"], "DMROverlord" },
		{ AL["Elder Hollowblood"], "DMRElderHollowblood" },
		{ AL["Searistrasz"], "DMRSearistrasz" },
		{ AL["Zuluhed the Whacked"], "DMRZuluhed" },
		{ AL["Trash Mobs"], "DMRTrash" },
	},
	["StormwroughtRuins"] = {
		{ AL["Oronok Torn-Heart"], "SWROronok" },
		{ AL["Dagar the Glutton"], "SWRDagar" },
		{ AL["Duke Balor the IV"], "SWRDukeBalor" },
		{ AL["Librarian Theodorus"], "SWRLibrarian" },
		{ AL["Chieftain Stormsong"], "SWRChieftain" },
		{ AL["Deathlord Tidebane"], "SWRDeathlord" },
		{ AL["Subjugator Halthas Shadecrest"], "SWRSubjugator" },
		{ AL["Mycellakos"], "SWRMycellakos" },
		{ AL["Eldermaw the Primordial"], "SWREldermaw" },
		{ AL["Lady Drazare"], "SWRLadyDrazare" },
		{ AL["Remains of the Innocent"], "SWRRemains" },
		{ AL["Mergothid"], "SWRMergothid" },
		{ AL["Trash Mobs"], "SWRTrash" },
	},
}
